### ISSUE TITLE
3.0.0-M2 epic

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon-build-tools#550]
- [x] Bug fixes on basic functionality to be on par with V1.
- [x] Cli batch support
  - #543
- [x] Maven support
   - #544 
   - #547
- [x] Fully functional archetype maven module in Helidon
  - #545
  - #547
- [x] Starter REST API
  - #546
- [x] Demo
  -  #566
