### ISSUE TITLE
Functional test for CLI

### ISSUE THREAD

**Issue by tvallin** [oracle/helidon-build-tools#652]
Start implementing test suite for the CLI. Take a look at Bedrock as a test framework that can drive the CLI like a user would.

Define use cases and implement tests.

  - [x] see https://github.com/oracle/helidon-build-tools/issues/651
  - [x] see https://github.com/oracle/helidon-build-tools/issues/650
  - [x] see https://github.com/oracle/helidon-build-tools/issues/649
  - [x] see https://github.com/oracle/helidon-build-tools/issues/565
